### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Abbe98** [rielc/DDBViz#2]
Could this code be assigned an open license?

**Comment by rielc** [comment]
Yeah, we probably should have some proper license. However I would like some confirmation from @nrchtct (esp. for the data part of this repo)?

**Comment by nrchtct** [comment]
the code for sure, and the data i am not so sure. will ask our partners

**Comment by cpietsch** [comment]
What license should we use ? MIT or GPL ?

**Comment by gitstief** [comment]
Hi, I am Stephan Bartholmei from the German Digital Library  (DDB) and @cpietsch's & @nrchtct's partner within this project. All of the metadata in DDB except for longer descriptions (that are usually found for museum objects), are under CC0. But, I am pretty sure, that the information from the description wasn't used in this project.

**Comment by cpietsch** [comment]
Thx @gitstief. I can confirm that we didn't use the descriptions.

**Comment by nrchtct** [comment]
MIT would probly make things easier for our friends up north. what do you think, @cpietsch & @rielc?

**Comment by rielc** [comment]
+1 for MIT

**Comment by Abbe98** [comment]
For our use case it would be totally fine if the data would remin under copyright.

**Comment by Abbe98** [comment]
This is a gentle reminder that this issue still remains. :coffee:

**Comment by cpietsch** [comment]
done 021dd66c4fc6ad98bf9539ca5b072201d742114a
